name: web

on:
  push:
    branches: [ master ]

orbs:
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    runs-on: macos-latest
    docker:
      - image: cimg/openjdk:11.0.16-browsers

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Display Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: test open browser
        run:  
          set +e
          mvn clean verify -Dtags='@openWeb'
          echo Test finalizado, revise el reporte

      - name: test login user
        run:
          set +e
          mvn clean verify -Dtags='@login'
          echo Test finalizado, revise el reporte

      - name: test resgister user
        run:
          set +e
          mvn clean verify -Dtags='@register'
          echo Test finalizado, revise el reporte
