name: Run Selenium Tests with Java

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptium'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.8.1'

      - name: Install Google Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          
          sudo apt-get install -y google-chrome-stable

          CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Selenium tests in headless mode
        run: mvn test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes
