name: Run Selenium Tests with Java 8

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # 3. Instalar Google Chrome y ChromeDriver
      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y google-chrome-stable
          
          CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 4. Ejecutar las pruebas con Maven (sin compilar, solo pruebas)
      - name: Run tests with Maven
        run: mvn test
