name: Run Selenium Tests with Java

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up JDK 8 (especifica java-version: '8')
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          # Optional: If you want a specific distribution, you can use 'adoptopenjdk' or 'adoptium'
          distribution: 'adoptium'  # Si no es necesario, puedes omitirlo ya que el valor por defecto es adecuado

      # 3. Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # 4. Install Google Chrome and Chromedriver
      - name: Install Google Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y google-chrome-stable
          
          CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 5. Build the project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 6. Run Selenium tests in headless mode
      - name: Run Selenium tests in headless mode
        run: mvn test

      # 7. Upload test results (using v3)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes
