name: Run Selenium Tests with Java

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up JDK 11 (You can specify `distribution` or leave it out for the default OpenJDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          # Optional: specify distribution. Defaults to 'adoptopenjdk'
          distribution: 'adoptopenjdk'  # You can also remove this line, as GitHub Actions will use 'adoptopenjdk' by default.

      # 3. Set up Maven separately (No maven-version in setup-java)
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # 4. Install Google Chrome and Chromedriver
      - name: Install Google Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y google-chrome-stable
          
          CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 5. Build the project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 6. Run Selenium tests in headless mode
      - name: Run Selenium tests in headless mode
        run: mvn test

      # 7. Upload test results (using v3)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes
