name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Display Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test open browser
        run: |
          mvn clean verify -Dtags='openWeb'
          echo "Test finalizado, revise el reporte"

      - name: Test login user
        run: |
          mvn clean verify -Dtags='login'
          echo "Test finalizado, revise el reporte"

      - name: Test register user
        run: |
          mvn clean verify -Dtags='register'
          echo "Test finalizado, revise el reporte"
